# Generated by Django 3.0.4 on 2021-04-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddLicense',
            fields=[
                ('Date', models.DateField(auto_now=True, max_length=8)),
                ('RequestNo', models.IntegerField(primary_key=True, serialize=False)),
                ('PlanName', models.CharField(max_length=150)),
                ('TotalUsers', models.IntegerField()),
                ('AddUsers', models.IntegerField()),
                ('LicensesAfter', models.IntegerField()),
                ('EffectiveDate', models.DateField(auto_now=True, max_length=8)),
                ('ActiveFlag', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'AddLicense',
            },
        ),
        migrations.CreateModel(
            name='ReduceLicense',
            fields=[
                ('Date', models.DateField(auto_now=True, max_length=8)),
                ('RequestNo', models.IntegerField(primary_key=True, serialize=False)),
                ('PlanName', models.CharField(max_length=150)),
                ('TotalUsers', models.IntegerField()),
                ('ReduceUsers', models.IntegerField()),
                ('LicensesAfter', models.IntegerField()),
                ('EffectiveDate', models.DateField(auto_now=True, max_length=8)),
                ('ActiveFlag', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ReduceLicense',
            },
        ),
        migrations.CreateModel(
            name='RequestForCancelPlan',
            fields=[
                ('RequestNo', models.IntegerField(primary_key=True, serialize=False)),
                ('NoOfUsers', models.IntegerField()),
                ('EffectiveDate', models.DateField(auto_now=True, max_length=8)),
                ('PlanName', models.CharField(max_length=150)),
                ('ExpiryDate', models.DateField(auto_now=True, max_length=8)),
            ],
            options={
                'db_table': 'RequestForCancelPlan',
            },
        ),
    ]
