# Generated by Django 3.0.4 on 2021-04-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temporary', '0003_myjobdescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('EnquiryDate', models.DateField(auto_now=True, max_length=8)),
                ('EnquiryNo', models.IntegerField(primary_key=True, serialize=False)),
                ('CustomerName', models.CharField(max_length=150)),
                ('Description', models.CharField(max_length=150)),
                ('NoOfUsers', models.IntegerField()),
                ('LeadNo', models.IntegerField()),
                ('ActiveFlag', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Enquiry',
            },
        ),
    ]
