# Generated by Django 3.0.4 on 2021-04-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temporary', '0004_enquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTime', models.DateTimeField()),
                ('TicketNo', models.IntegerField()),
                ('TicketSubject', models.CharField(max_length=150)),
                ('TicketStatus', models.BooleanField()),
                ('DateOfCompletion', models.DateField(auto_now=True, max_length=8)),
            ],
            options={
                'db_table': 'Tickets',
            },
        ),
        migrations.DeleteModel(
            name='AddLicense',
        ),
        migrations.DeleteModel(
            name='CancellationPlan',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='CustomerMaster',
        ),
        migrations.DeleteModel(
            name='Enquiry',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='JobBrief',
        ),
        migrations.DeleteModel(
            name='JobCategory',
        ),
        migrations.DeleteModel(
            name='JobInterviewQuestion',
        ),
        migrations.DeleteModel(
            name='JobPosting',
        ),
        migrations.DeleteModel(
            name='JobRequirement',
        ),
        migrations.DeleteModel(
            name='JobResponsibility',
        ),
        migrations.DeleteModel(
            name='JobTitle',
        ),
        migrations.DeleteModel(
            name='MyJobDescription',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Perks',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='Qualification',
        ),
        migrations.DeleteModel(
            name='ReduceLicense',
        ),
        migrations.DeleteModel(
            name='RequestForCancelPlan',
        ),
        migrations.DeleteModel(
            name='SalesLead',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='State',
        ),
        migrations.DeleteModel(
            name='Subscriptions',
        ),
        migrations.DeleteModel(
            name='UserMaster',
        ),
    ]
